version: '3.9'

services:
  parser_nft:
    build: ./
    restart: always
    environment:
      - KAFKA_GROUP_ID=nft_history
      - SUPPORTED_PARSERS=NftHistoryParser
      - KAFKA_TOPICS=ton.public.nft_transfers
      - COMMIT_BATCH_SIZE=20
    env_file:
      - parser.env
    logging:
      driver: local
      options:
        max-size: 10M

  parser_core_prices:
    build: ./
    restart: always
    environment:
      - KAFKA_GROUP_ID=core_prices
      - SUPPORTED_PARSERS=CorePricesUSDT,CorePricesLSDstTON,CorePricesLSDtsTON
      - KAFKA_TOPICS=ton.public.latest_account_states
      - KAFKA_OFFSET_RESET=latest
      - COMMIT_BATCH_SIZE=1
    env_file:
      - parser.env
    logging:
      driver: local
      options:
        max-size: 10M

  parser_messages:
    build: ./
    restart: always
    environment:
      - KAFKA_GROUP_ID=messages_parsers
      - SUPPORTED_PARSERS=StonfiSwap,DedustSwap
      - KAFKA_TOPICS=ton.public.messages
    env_file:
      - parser.env
    logging:
      driver: local
      options:
        max-size: 10M

  parser_messages_comments:
    build: ./
    restart: always
    environment:
      - KAFKA_GROUP_ID=messages_contents
      - SUPPORTED_PARSERS=CommentsDecoder
      - KAFKA_TOPICS=ton.public.message_contents
    env_file:
      - parser.env
    logging:
      driver: local
      options:
        max-size: 10M

  parser_nfts_recover:
    build: ./
    restart: always
    environment:
      - KAFKA_GROUP_ID=recovery_nfts
      - SUPPORTED_PARSERS=NFTsRecover
      - KAFKA_TOPICS=ton.public.latest_account_states
    env_file:
      - parser.env
    logging:
      driver: local
      options:
        max-size: 10M


networks:
  default:
    name: data_default
    external: true